apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cities-api.fullname" . }}
  labels:
    {{- include "cities-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cities-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cities-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: OPENSEARCH_HOST
              valueFrom:
                secretKeyRef:
                  name: opensearch
                  key: host
            - name: OPENSEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: opensearch
                  key: user
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensearch
                  key: password
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
